#!/usr/bin/env bash

bspc monitor -d term web code music irssi VII VIII IX X

$HOME/.config/polybar/launch.sh &
sxhkd &

bspc config border_width         10
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

color_focused_border="#6162ae"
color_normal_border="#282a37"
color_active_border="#282a37"
color_presel_feedback="#9966cc"

setting_borderless_monocle='false'

