#!/usr/bin/env bash
feh --bg-scale Pictures/dracula.png &
sxhkd &
compton &

bspc monitor eDP1 -d term web code music irssi VII VIII IX X

$HOME/.config/polybar/launch.sh &

bspc config border_width         10
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chrome desktop='^2'
bspc rule -a llpp desktop=^8

#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc config focused_border_color #bd93f9
bspc config normal_border_color #6272a4

setting_borderless_monocle='false'
#if xrandr | grep -q "DP1 connected"; then
#bspc monitor eDP1 -d term web code music irssi 
#bspc monitor DP1 -d VII VIII IX X
#fi
